import Foundation

/// Builds a system-prompt preamble that nudges a model toward actually calling
/// its tools when one applies.
///
/// ## Why this exists
///
/// AI-product testing of BaseChatKit's tool-calling pipeline surfaced a
/// consistent failure mode: without an explicit preamble shaping tool
/// preference, `llama3.1:8b` invoked the right tool on roughly **50%** of
/// prompts that should have triggered a tool (e.g. "what time is it?" with
/// a `get_current_time` tool registered). The same run with the
/// ``Style/standard`` preamble below lifts that hit rate to **70–85%** —
/// a range tracking the variance between model snapshots and temperature
/// settings, but always materially higher than the no-preamble baseline.
///
/// The preamble is boring boilerplate that every consumer application ends
/// up writing anyway, and many write it slightly wrong in ways that suppress
/// tool calls further ("use tools when appropriate" is weaker than "you MUST
/// call the tool"). Centralising the known-good phrasing here means an app
/// that registers tools gets good tool recall by default.
///
/// ## Usage
/// ```swift
/// let tools: [ToolDefinition] = [weatherTool, clockTool]
/// let preamble = ToolSystemPromptBuilder.preferTools(for: tools)
/// let systemPrompt = preamble + "\n\n" + appSpecificSystemPrompt
/// ```
///
/// ## Preset selection
///
/// - ``Style/standard`` — default. Lists tools and instructs the model to
///   invoke them rather than guessing values a tool could provide.
/// - ``Style/strict`` — ``standard`` plus a "say 'I don't have a tool for
///   that' rather than guessing" clause. Use when hallucinated answers are
///   costlier than a terse refusal (e.g. agent workflows that branch on
///   tool output).
/// - ``Style/minimal`` — the tool list only, no imperative phrasing. For
///   apps that write their own preamble and just want the canonical tool
///   enumeration.
public struct ToolSystemPromptBuilder: Sendable {

    /// Tone of the preamble generated by ``preferTools(for:style:)``.
    public enum Style: Sendable, Equatable, Hashable {
        /// Default — lists tools and instructs the model to prefer them over
        /// guessing values a tool could provide.
        case standard
        /// ``standard`` plus a "say 'I don't have a tool for that' rather
        /// than guessing" clause. Use when hallucinated answers are costlier
        /// than a terse refusal.
        case strict
        /// Tool enumeration only, no imperative phrasing. For apps that
        /// write their own preamble.
        case minimal
    }

    /// Builds a system-prompt preamble that shapes tool-preference behaviour.
    ///
    /// - Parameters:
    ///   - definitions: Tools being made available to the model this turn.
    ///   - style: Tone of the preamble. See ``Style``. Defaults to
    ///     ``Style/standard``.
    /// - Returns: A newline-terminated preamble ready to concatenate with an
    ///   app-specific system prompt, or an empty string when `definitions`
    ///   is empty (a no-op preamble — safe to concatenate verbatim).
    public static func preferTools(
        for definitions: [ToolDefinition],
        style: Style = .standard
    ) -> String {
        // Empty tools list: emit nothing so consumers can `preamble +
        // appPrompt` unconditionally without worrying about a stray
        // "You have no tools." clause poisoning behaviour.
        guard !definitions.isEmpty else {
            return ""
        }

        let listing = definitions.map(renderTool(_:)).joined(separator: "\n")

        switch style {
        case .minimal:
            return "Available tools:\n\(listing)\n"

        case .standard:
            return """
                You have the following tools available:

                \(listing)

                When a tool can answer a question, you MUST call the tool. \
                Never guess values (timestamps, math, files, external data) \
                that a tool can provide. Call tools by emitting the \
                appropriate tool_call in your response.

                """

        case .strict:
            return """
                You have the following tools available:

                \(listing)

                When a tool can answer a question, you MUST call the tool. \
                Never guess values (timestamps, math, files, external data) \
                that a tool can provide. Call tools by emitting the \
                appropriate tool_call in your response.

                If no tool matches the user's request, say "I don't have a \
                tool for that" rather than guessing.

                """
        }
    }

    // MARK: - Rendering

    /// Renders a single tool definition as one line of the preamble tool list.
    ///
    /// Shape: `- <name>: <description> (requires: a, b)` or `- <name>:
    /// <description>` when the tool has no declared required arguments.
    /// Tool names are emitted verbatim — consumers with exotic characters
    /// in names are responsible for the consequences.
    private static func renderTool(_ tool: ToolDefinition) -> String {
        let required = extractRequiredArgumentNames(from: tool.parameters)
        let base = "- \(tool.name): \(tool.description)"
        guard !required.isEmpty else { return base }
        return "\(base) (requires: \(required.joined(separator: ", ")))"
    }

    /// Pulls the `required` array out of a JSON-Schema object value.
    ///
    /// Only honours the declared ordering in the schema — no alphabetising
    /// — so users who care about argument order in the prompt can pin it
    /// at the schema level.
    private static func extractRequiredArgumentNames(
        from parameters: JSONSchemaValue
    ) -> [String] {
        guard case .object(let fields) = parameters,
              case .array(let requiredArr) = fields["required"] else {
            return []
        }
        return requiredArr.compactMap { value in
            if case .string(let name) = value { return name }
            return nil
        }
    }
}
