name: Actionlint

on:
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/**"
      - ".github/actionlint*"
  push:
    branches: [main]
    paths:
      - ".github/workflows/**"
      - ".github/actionlint*"

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint GitHub Actions workflows
        uses: rhysd/actionlint@v1
